# Generated by Django 4.2.1 on 2023-05-19 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_book_seat_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='pass_age',
            field=models.IntegerField(default=0, max_length=2),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='book',
            name='pass_gender',
            field=models.CharField(default='Male', max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='book',
            name='pass_name',
            field=models.CharField(default='sample', max_length=50),
            preserve_default=False,
        ),
    ]
