# Generated by Django 4.2.1 on 2023-05-24 12:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_remove_book_no_seats'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user_details',
            name='gender',
        ),
    ]
