# Generated by Django 4.2.1 on 2023-06-01 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_user_details_last_login'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='bus_name',
            new_name='bus_type',
        ),
        migrations.RenameField(
            model_name='bus_details',
            old_name='bus_name',
            new_name='bus_type',
        ),
        migrations.AddField(
            model_name='book',
            name='admin_id',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='book',
            name='travels_name',
            field=models.CharField(default='a', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='bus_details',
            name='admin_id',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='bus_details',
            name='travels_name',
            field=models.CharField(default='a', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='book',
            name='pass_age',
            field=models.IntegerField(),
        ),
    ]
