# Generated by Django 4.2.1 on 2023-06-01 09:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_rename_bus_name_book_bus_type_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='admin_id',
        ),
    ]
