# Generated by Django 4.2.1 on 2023-06-07 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_remove_book_admin_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='trip_status',
            field=models.CharField(default='Yet to start', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='bus_details',
            name='bus_status',
            field=models.CharField(default='Yet to start', max_length=20),
            preserve_default=False,
        ),
    ]
