# Generated by Django 4.2.1 on 2023-05-30 15:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('custom_admin', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='additional_field',
            new_name='organisation',
        ),
    ]
