# Generated by Django 4.2.1 on 2023-05-17 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_user_details'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_details',
            name='gender',
            field=models.CharField(default='Male', max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user_details',
            name='mailid',
            field=models.CharField(default='123@gmail.com', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user_details',
            name='name',
            field=models.CharField(default='abc', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user_details',
            name='password',
            field=models.CharField(default='sample', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user_details',
            name='repassword',
            field=models.CharField(default='sample', max_length=20),
            preserve_default=False,
        ),
    ]
