# Generated by Django 4.2.1 on 2023-05-17 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_user_details_gender_user_details_mailid_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.DecimalField(decimal_places=0, max_digits=2)),
                ('bus_id', models.DecimalField(decimal_places=0, max_digits=2)),
                ('name', models.CharField(max_length=50)),
                ('mailid', models.EmailField(max_length=254)),
                ('bus_name', models.CharField(max_length=50)),
                ('source', models.CharField(max_length=50)),
                ('dest', models.CharField(max_length=50)),
                ('no_seats', models.DecimalField(decimal_places=0, max_digits=2)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('status', models.CharField(choices=[('B', 'Booked'), ('C', 'Cancelled')], default='B', max_length=3)),
            ],
        ),
    ]
