# Generated by Django 4.2.1 on 2023-05-19 12:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_book_pass_age_book_pass_gender_book_pass_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='no_seats',
        ),
    ]
